CREATE TABLE BANK2000.basis.STATISTICS_TEST (
ID INT IDENTITY(1,1) PRIMARY KEY,
Debit_Segment VARCHAR(20),
Credit_Segment Varchar(20),
ChannelID INT ,
OP_Date DATE,
OP_Count INT DEFAULT 0,

CONSTRAINT UQ_Stats UNIQUE (Debit_Segment, Credit_Segment, ChannelID, OP_Date)
);

SELECT * FROM  BANK2000.basis.STATISTICS_TEST


TRUNCATE TABLE BANK2000.basis.STATISTICS_TEST

SELECT * FROM  BANK2000.dbo.CLIENT_ATTRIBUTES
WHERE ATTRIB_VALUE LIKE ''

SELECT TOP 10 C.CLIENT_NO, C.IS_JURIDICAL, ATT.ATTRIB_CODE
FROM BANK2000.dbo.CLIENTS AS C
LEFT JOIN BANK2000.dbo.CLIENT_ATTRIBUTES AS ATT 
    ON ATT.CLIENT_NO = C.CLIENT_NO
    AND ATT.ATTRIB_CODE IN ('UNIQUE_BANKER', 'PREMIUM_BANKER')
WHERE C.IS_JURIDICAL = 0
AND ATT.ATTRIB_CODE IS NULL 


SELECT TOP 100 CLIENT_NO
FROM BANK2000.dbo.CLIENTS
WHERE PERSONAL_ID='01011094033'